name: MRW Daemon
on: [push]

jobs:
  MRW-Daemon:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./daemon
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: make depend
      - name: Build
        run: make -j `nproc`
